spring:
  application:
    name: spring-batch-demo

  flyway:
    enabled: false
    locations: "classpath:db,filesystem:/opt/migration"

    datasource:
      url: jdbc:postgresql://localhost:5432/postgres
      username: postgres
      password: postgres

  jpa:
    open-in-view: false
    hibernate:
        ddl-auto: update # create-drop, create, update, validate, none
        show-sql: true
